# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

load "../Vagrantfile-base"

Vagrant.configure(2) do |config|
  config.vm.provision :shell, inline: <<-SHELL
    # Create vagrant_data folder
    sudo mkdir -p /vagrant_data /vagrant_local
    sudo chown vagrant:vagrant /vagrant_data /vagrant_local
    # Zero free space to aid VM compression
    sudo dd if=/dev/zero of=/EMPTY bs=1M
    sudo rm -f /EMPTY
  SHELL
  config.vm.provision :file, source: "../sync", destination: "/vagrant_data"
  config.vm.provision :file, source: "../sync/local", destination: "/vagrant_local"
end
